/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#3f465c',
        'inverse-primary': '#c3c0ff',
        'surface-container': '#eceef0',
        'on-background': '#191c1e',
        'tertiary-fixed': '#e1e0ff',
        'secondary-container': '#dae2fd',
        'surface-variant': '#e0e3e5',
        'surface-container-highest': '#e0e3e5',
        'surface-tint': '#4d44e3',
        'on-primary-fixed': '#0f0069',
        surface: '#f7f9fb',
        'on-primary-fixed-variant': '#3323cc',
        'surface-container-high': '#e6e8ea',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed': '#dae2fd',
        'on-surface-variant': '#464555',
        'surface-dim': '#d8dadc',
        'outline-variant': '#c7c4d8',
        'on-secondary-container': '#5c647a',
        'on-secondary-fixed': '#131b2e',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-container': '#d9d8ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'primary-fixed-dim': '#c3c0ff',
        'primary-container': '#4f46e5',
        'surface-bright': '#f7f9fb',
        'on-surface': '#191c1e',
        'on-primary': '#ffffff',
        primary: '#3525cd',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        error: '#ba1a1a',
        secondary: '#565e74',
        'inverse-surface': '#2d3133',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#c0c1ff',
        background: '#f7f9fb',
        'primary-fixed': '#e2dfff',
        tertiary: '#3130c0',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#dad7ff',
        outline: '#777587',
        'secondary-fixed-dim': '#bec6e0',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4b4dd8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        'margin-desktop': '48px',
        'stack-md': '16px',
        gutter: '24px',
        'stack-lg': '32px',
        unit: '4px',
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'container-max': '1440px',
        section: '128px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'ai-stat': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      boxShadow: {
        soft: '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        lift: '0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.08)',
        'ambient-sm': '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        'ambient-md': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
